version: '3'

services:
  mongo1:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDB2019!
    ports:
      - '27017:27017'
    links:
      - mongo2
      - mongo3
    volumes:
      - dbdata1:/data/db
    networks:
      - mongo-compose-network
    entrypoint: ['/usr/bin/mongod', '--bind_ip_all', '--replSet', 'dbrs']
  mongo2:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDB2019!
    ports:
      - '27018:27017'
    volumes:
      - dbdata2:/data/db
    networks:
      - mongo-compose-network
    entrypoint: ['/usr/bin/mongod', '--bind_ip_all', '--replSet', 'dbrs']
  mongo3:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDB2019!
    ports:
      - '27019:27017'
    volumes:
      - dbdata3:/data/db
    networks:
      - mongo-compose-network
    entrypoint: ['/usr/bin/mongod', '--bind_ip_all', '--replSet', 'dbrs']

volumes:
  dbdata1:
  dbdata2:
  dbdata3:

networks:
  mongo-compose-network:
    driver: bridge
